theme: jekyll-theme-minimal
description: >

  A thoroughly documented repository detailing the full construction of a custom-made RC plane, incorporating specific aerodynamic principles, materials, and designs to create a craft optimized for power, lift, and manuverability.
  
  * **Model Type:** High-Wing UAV <br>
  * **Wingspan:** 508mm <br>
  * **Propulsion:** FT Radial 2212-1050kV <br>
  * **Airfoil:** Modified Kfm-1 <br>
  * **Material:** EPS Foamboard <br>
  * **Weight:** 0.42 lb (190.5g)
