theme: jekyll-theme-minimal
title: RC High Wing Trainer
description: >
  A documented repository detailing the construction of a custom-made RC plane, incorporating specific aerodynamic principles, build materials, and components to create a craft optomized for lift, high weight-power ratios and extreme manuverability.<br>
  <br>
  <b>Model Type:</b> High-Wing UAV<br>
  <b>Wingspan:</b> 508mm<br>
  <b>Propulsion:</b> FT Radial 2212-1050kV<br>
  <b>Airfoil:</b> Modified Kfm-1<br>
  <b>Weight:</b> 0.42 lb (190.5g)<br>
  <b>Battery Type:<b> 11.1V 3S 1300mAh<br>
  <b>Flight Time:</b> ~8 minutes/battery (mixed throttle)
