theme: jekyll-theme-minimal
title: RC High-Wing Trainer
description: |
  A documented repository detailing the construction of a custom-made RC plane.

  Model Type: High-Wing UAV
  
  Wingspan: 508mm
  
  Propulsion: FT Radial 2212-1050kV
  
  Airfoil: Modified Kfm-1
  
  Weight: 0.42 lb (190.5g)
